import type { Template, MapStyle } from './types';
import { FONTS } from './fonts';

const baseStyle: MapStyle = {
  backgroundColor: '#f5f5f0',
  mainDepartmentColor: '#e8e6df',
  mainDepartmentOpacity: 1,
  neighborDepartmentColor: '#ededea',
  neighborDepartmentOpacity: 0.8,
  borderColor: '#3b6fa0',
  borderWidth: 1.5,
  borderOpacity: 1,
  borderLineJoin: 'round',
  borderDash: 'solid',
  circleColor: '#f97316',
  circleOpacity: 0.15,
  circleBorderColor: '#f97316',
  circleDash: 'dashed',
  markerColor: '#f97316',
  markerSize: 12,
  markerType: 'dot',
  secondaryMarkerColor: '#64748b',
  mainTextColor: '#c2410c',
  secondaryTextColor: '#475569',
  fontFamily: FONTS[0].stack,
  labelOutlineWidth: 0,
  labelOutlineColor: '#ffffff',
  showDeptNumber: true,
  showDeptName: false,
  deptLabelSize: 28,
  deptLabelColor: '#c8c4bb',
  deptLabelWeight: 800,
  deptLabelFilled: true,
};

export const TEMPLATES: Template[] = [
  {
    id: 'seo',
    label: 'SEO Pro',
    description: 'Style professionnel pour sites artisans et entreprises locales',
    style: { ...baseStyle },
  },
  {
    id: 'blue',
    label: 'Bleu Corporate',
    description: 'Style bleu institutionnel, idéal pour services et professions libérales',
    style: {
      ...baseStyle,
      backgroundColor: '#f0f4f8',
      mainDepartmentColor: '#dce8f5',
      neighborDepartmentColor: '#eaf1f8',
      borderColor: '#1d4ed8',
      circleColor: '#3b82f6',
      circleBorderColor: '#2563eb',
      markerColor: '#1d4ed8',
      secondaryMarkerColor: '#64748b',
      mainTextColor: '#1e3a8a',
      secondaryTextColor: '#475569',
      deptLabelColor: '#b8cce4',
    },
  },
  {
    id: 'orange',
    label: 'Orange BTP',
    description: 'Style vif pour BTP, déménagement, logistique',
    style: {
      ...baseStyle,
      backgroundColor: '#fefce8',
      mainDepartmentColor: '#fef9c3',
      neighborDepartmentColor: '#fefce8',
      borderColor: '#d97706',
      circleColor: '#f59e0b',
      circleBorderColor: '#d97706',
      markerColor: '#d97706',
      secondaryMarkerColor: '#92400e',
      mainTextColor: '#92400e',
      secondaryTextColor: '#78350f',
      deptLabelColor: '#f0d88a',
    },
  },
  {
    id: 'minimal',
    label: 'Minimaliste',
    description: 'Style épuré, fond transparent, pour intégration web',
    style: {
      ...baseStyle,
      backgroundColor: '#ffffff',
      mainDepartmentColor: '#f1f5f9',
      neighborDepartmentColor: '#f8fafc',
      borderColor: '#94a3b8',
      borderWidth: 1,
      circleColor: '#334155',
      circleOpacity: 0.08,
      circleBorderColor: '#334155',
      markerColor: '#0f172a',
      secondaryMarkerColor: '#94a3b8',
      mainTextColor: '#0f172a',
      secondaryTextColor: '#64748b',
      deptLabelColor: '#d1d5db',
      showDeptNumber: false,
      showDeptName: false,
    },
  },
  {
    id: 'artisan',
    label: 'Artisan',
    description: 'Chaud et naturel, idéal pour artisans, plombiers, électriciens',
    style: {
      ...baseStyle,
      backgroundColor: '#fdf8f3',
      mainDepartmentColor: '#f5ede0',
      neighborDepartmentColor: '#faf5ee',
      borderColor: '#92400e',
      circleColor: '#b45309',
      circleBorderColor: '#92400e',
      markerColor: '#b45309',
      secondaryMarkerColor: '#78350f',
      mainTextColor: '#7c2d12',
      secondaryTextColor: '#92400e',
      deptLabelColor: '#d4b896',
      fontFamily: FONTS.find(f => f.id === 'oswald')?.stack ?? baseStyle.fontFamily,
    },
  },
];

export function getTemplate(id: string): Template {
  return TEMPLATES.find((t) => t.id === id) ?? TEMPLATES[0];
}
